// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Verisoft.Codereview.DotnetAspire.Database;

#nullable disable

namespace Verisoft.Codereview.DotnetAspire.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240216123518_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Verisoft.Codereview.DotnetAspire.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4e5baf9-25fc-15a7-e4a8-0ebc1e20a251"),
                            Description = "This product works considerably well. It recklessly improves my basketball by a lot.",
                            FirstName = "Selma",
                            LastName = "Rácová",
                            Name = "Selma56"
                        },
                        new
                        {
                            Id = new Guid("f75f517c-f46a-9487-97ba-d45594ac18d0"),
                            Description = "The box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!",
                            Email = "Johana_Karlikova@volny.cz",
                            FirstName = "Johana",
                            LastName = "Karlíková",
                            Name = "Johana_Karlikova54"
                        },
                        new
                        {
                            Id = new Guid("00683601-0eb1-f107-cf71-b984b184320c"),
                            Email = "Sofronie.Waltrova16@atlas.cz",
                            FirstName = "Sofronie",
                            LastName = "Waltrová",
                            Name = "Sofronie.Waltrova11"
                        },
                        new
                        {
                            Id = new Guid("e29ae6d2-6a26-ec04-b692-5c5cd8ad264a"),
                            Description = "i use it every Tuesday when i'm in my pub.",
                            FirstName = "Bertram",
                            LastName = "Hovorka",
                            Name = "Bertram_Hovorka"
                        },
                        new
                        {
                            Id = new Guid("50ccd97f-fc46-a70c-e695-2c6dd5993817"),
                            Description = "I saw one of these in Juan de Nova Island and I bought one.",
                            FirstName = "Magda",
                            LastName = "Neumannová",
                            Name = "Magda.Neumannova60"
                        },
                        new
                        {
                            Id = new Guid("53e962af-7a6c-67af-a8d3-55ad840d9f74"),
                            Email = "Edmund73@seznam.cz",
                            FirstName = "Edmund",
                            LastName = "Anděl",
                            Name = "Edmund.Andel85"
                        },
                        new
                        {
                            Id = new Guid("017556a4-6f74-d940-0639-606c3fa16603"),
                            FirstName = "Konstance",
                            LastName = "Krupková",
                            Name = "Konstance94"
                        },
                        new
                        {
                            Id = new Guid("1603d0ec-966e-9fe4-8b44-fabebf72587e"),
                            Description = "I tried to vomit it but got bonbon all over it.",
                            FirstName = "Koloman",
                            LastName = "Černík",
                            Name = "Koloman_Cernik"
                        },
                        new
                        {
                            Id = new Guid("e746b2db-d3c3-b4fa-8c78-67476c4be551"),
                            Email = "Horymira_Rysava37@gmail.com",
                            FirstName = "Horymíra",
                            LastName = "Ryšavá",
                            Name = "Horymira_Rysava7"
                        },
                        new
                        {
                            Id = new Guid("7098a8a2-f284-64ba-22ce-8f6963c4781e"),
                            FirstName = "Arnolda",
                            LastName = "Zoubková",
                            Name = "Arnolda_Zoubkova6"
                        },
                        new
                        {
                            Id = new Guid("a1331be4-7f6f-0de7-5081-fcf93deabc8b"),
                            FirstName = "Alina",
                            LastName = "Čápová",
                            Name = "Alina_Capova59"
                        },
                        new
                        {
                            Id = new Guid("6ec37119-cadf-bedd-7e05-eaed4b405607"),
                            Description = "one of my hobbies is theater. and when i'm acting this works great.",
                            FirstName = "Verner",
                            LastName = "Prchal",
                            Name = "Verner40"
                        },
                        new
                        {
                            Id = new Guid("7db295c2-d59a-d12f-1719-4a77e33a3d1b"),
                            Description = "My neighbor Krista has one of these. She works as a salesman and she says it looks soapy.",
                            Email = "Gajana87@atlas.cz",
                            FirstName = "Gajana",
                            LastName = "Smolíková",
                            Name = "Gajana.Smolikova15"
                        },
                        new
                        {
                            Id = new Guid("ebcb49ba-6011-c2ed-ff8c-7ed4dec8571a"),
                            FirstName = "Darina",
                            LastName = "Šafářová",
                            Name = "Darina.Safarova"
                        },
                        new
                        {
                            Id = new Guid("c5387b51-a85d-3ccb-8cb6-9de27b0bac76"),
                            Email = "Benedikta.Vaculikova62@centrum.cz",
                            FirstName = "Benedikta",
                            LastName = "Vaculíková",
                            Name = "Benedikta_Vaculikova"
                        },
                        new
                        {
                            Id = new Guid("07f55226-879e-a9a7-a552-8c8333cf99d8"),
                            FirstName = "Vadim",
                            LastName = "Kubánek",
                            Name = "Vadim_Kubanek"
                        },
                        new
                        {
                            Id = new Guid("a916d7d6-eed8-e536-0112-a9291b2a1174"),
                            Email = "Chranislava_Kurkova94@gmail.com",
                            FirstName = "Chranislava",
                            LastName = "Kurková",
                            Name = "Chranislava_Kurkova46"
                        },
                        new
                        {
                            Id = new Guid("d736e495-fe53-db50-04ab-c3df3205cd48"),
                            FirstName = "Mahulena",
                            LastName = "Skácelová",
                            Name = "Mahulena.Skacelova0"
                        },
                        new
                        {
                            Id = new Guid("34531f20-4a76-1c61-c5f2-ca6552955546"),
                            Description = "I tried to maim it but got nectarine all over it.",
                            FirstName = "Bela",
                            LastName = "Žďárská",
                            Name = "Bela94"
                        },
                        new
                        {
                            Id = new Guid("a6382d69-d2e1-f8bc-643a-a4a0726a3519"),
                            Email = "Kleopatra.Pelikanova@seznam.cz",
                            FirstName = "Kleopatra",
                            LastName = "Pelikánová",
                            Name = "Kleopatra.Pelikanova57"
                        },
                        new
                        {
                            Id = new Guid("7e380398-303f-a49a-60ac-698434bddb66"),
                            FirstName = "Herta",
                            LastName = "Bártová",
                            Name = "Herta.Bartova"
                        },
                        new
                        {
                            Id = new Guid("3c80b953-9f33-80fe-cade-c95378b67f9a"),
                            FirstName = "Felix",
                            LastName = "Winkler",
                            Name = "Felix48"
                        },
                        new
                        {
                            Id = new Guid("d3e9e8f9-a643-4a0c-b4dd-4bd7765f25b7"),
                            Description = "My neighbor Frona has one of these. She works as a gambler and she says it looks bearded.",
                            FirstName = "Lucius",
                            LastName = "Fišer",
                            Name = "Lucius.Fiser"
                        },
                        new
                        {
                            Id = new Guid("cc0b865b-6f73-2894-a1f6-1524a5881a42"),
                            FirstName = "Taras",
                            LastName = "Prchal",
                            Name = "Taras92"
                        },
                        new
                        {
                            Id = new Guid("13712058-787e-1073-984d-662f8d057898"),
                            Description = "This product works certainly well. It perfectly improves my tennis by a lot.",
                            FirstName = "Smil",
                            LastName = "Bouček",
                            Name = "Smil_Boucek99"
                        },
                        new
                        {
                            Id = new Guid("d81ba010-6c22-0bdb-9b22-fa633c9f5104"),
                            Description = "It only works when I'm Nepal.",
                            Email = "Tiberius60@seznam.cz",
                            FirstName = "Tiberius",
                            LastName = "Michal",
                            Name = "Tiberius_Michal"
                        },
                        new
                        {
                            Id = new Guid("23ebfa4b-83ac-3926-8578-6e8aa2acef4b"),
                            Description = "I tried to electrocute it but got sweetmeat all over it.",
                            FirstName = "Dominik",
                            LastName = "Koudelka",
                            Name = "Dominik12"
                        },
                        new
                        {
                            Id = new Guid("64055392-3011-fc60-a447-eaaf0596d03c"),
                            Description = "The box this comes in is 3 light-year by 5 meter and weights 10 ounce!",
                            Email = "Otomar_Rehacek88@seznam.cz",
                            FirstName = "Otomar",
                            LastName = "Řeháček",
                            Name = "Otomar_Rehacek2"
                        },
                        new
                        {
                            Id = new Guid("7b222fb7-9e47-f987-2b5a-d816c4594077"),
                            FirstName = "Alexandr",
                            LastName = "Kubica",
                            Name = "Alexandr42"
                        },
                        new
                        {
                            Id = new Guid("ec9653cf-c3a1-e3d4-15e8-586c32b18a56"),
                            Description = "i use it once a week when i'm in my firetruck.",
                            FirstName = "Bohuna",
                            LastName = "Šimáková",
                            Name = "Bohuna91"
                        },
                        new
                        {
                            Id = new Guid("43ff4694-d01c-1634-3863-7b19b5a1207c"),
                            Description = "one of my hobbies is sailing. and when i'm sailing this works great.",
                            FirstName = "Jarolíma",
                            LastName = "Wagnerová",
                            Name = "Jarolima.Wagnerova"
                        },
                        new
                        {
                            Id = new Guid("73ceb62f-2bb1-9878-10d2-7deed37850bc"),
                            Description = "talk about pleasure!",
                            Email = "Lola87@seznam.cz",
                            FirstName = "Lola",
                            LastName = "Ferencová",
                            Name = "Lola6"
                        },
                        new
                        {
                            Id = new Guid("89197b6d-1186-1784-95b7-9ed8517940ea"),
                            FirstName = "Milada",
                            LastName = "Zimová",
                            Name = "Milada28"
                        },
                        new
                        {
                            Id = new Guid("f68c447f-14b8-cf49-b2bc-a7c05dcb8613"),
                            Description = "I tried to annihilate it but got bonbon all over it.",
                            FirstName = "Virginie",
                            LastName = "Zelenková",
                            Name = "Virginie.Zelenkova"
                        },
                        new
                        {
                            Id = new Guid("0544b5cf-effa-a0a1-6ea9-9991dc002bc0"),
                            FirstName = "Konstantin",
                            LastName = "Krupa",
                            Name = "Konstantin59"
                        },
                        new
                        {
                            Id = new Guid("57cc98cd-91e9-4e92-b320-cabd18ab67fd"),
                            FirstName = "Julius",
                            LastName = "Bečvář",
                            Name = "Julius92"
                        },
                        new
                        {
                            Id = new Guid("1748aa58-0504-55a3-8cae-3897046adeee"),
                            Email = "Babeta_Richtrova@centrum.cz",
                            FirstName = "Babeta",
                            LastName = "Richtrová",
                            Name = "Babeta.Richtrova0"
                        },
                        new
                        {
                            Id = new Guid("7632ce15-8d19-f6ac-4119-5fca0da208a7"),
                            FirstName = "Eunika",
                            LastName = "Kupková",
                            Name = "Eunika_Kupkova"
                        },
                        new
                        {
                            Id = new Guid("68d39499-2253-7592-dcec-ca10025dcb73"),
                            Email = "Vojmir77@centrum.cz",
                            FirstName = "Vojmír",
                            LastName = "Krejčí",
                            Name = "Vojmir11"
                        },
                        new
                        {
                            Id = new Guid("80b4de82-5b6c-66b9-e751-dd7c725b4ccd"),
                            Description = "i use it from now on when i'm in my safehouse.",
                            Email = "Kristan.Michal@atlas.cz",
                            FirstName = "Křišťan",
                            LastName = "Michal",
                            Name = "Kristan_Michal"
                        },
                        new
                        {
                            Id = new Guid("e80189c0-6d94-8e61-9234-7ec918bf146a"),
                            Email = "Inocenc_Nedoma@seznam.cz",
                            FirstName = "Inocenc",
                            LastName = "Nedoma",
                            Name = "Inocenc.Nedoma"
                        },
                        new
                        {
                            Id = new Guid("9ff60a81-a76d-5f3a-fd04-5043fdbc21ea"),
                            Description = "one of my hobbies is toy collecting. and when i'm collecting toys this works great.",
                            FirstName = "Nona",
                            LastName = "Frydrychová",
                            Name = "Nona58"
                        },
                        new
                        {
                            Id = new Guid("8597e764-825b-0a22-a1d7-12920c2a435b"),
                            FirstName = "Věra",
                            LastName = "Samková",
                            Name = "Vera.Samkova"
                        },
                        new
                        {
                            Id = new Guid("acb9fbd4-74f9-7db2-fd8d-a3b10df4fa4e"),
                            Description = "heard about this on songo radio, decided to give it a try.",
                            FirstName = "Una",
                            LastName = "Dušková",
                            Name = "Una_Duskova"
                        },
                        new
                        {
                            Id = new Guid("89eee224-ad60-2668-6711-6c26256e5d2d"),
                            Email = "Bernard_Schejbal31@centrum.cz",
                            FirstName = "Bernard",
                            LastName = "Schejbal",
                            Name = "Bernard5"
                        },
                        new
                        {
                            Id = new Guid("8daab965-44ad-f078-cd55-14f9a2e3a272"),
                            Email = "Bela96@volny.cz",
                            FirstName = "Bela",
                            LastName = "Jansová",
                            Name = "Bela.Jansova70"
                        },
                        new
                        {
                            Id = new Guid("98a55ab1-8f9e-34ac-25a0-8293a3a5f9d1"),
                            Description = "This product works really well. It sympathetically improves my baseball by a lot.",
                            Email = "Zinaida.Adamova0@seznam.cz",
                            FirstName = "Zinaida",
                            LastName = "Adamová",
                            Name = "Zinaida.Adamova"
                        },
                        new
                        {
                            Id = new Guid("ac782d87-aa29-14d0-b2a0-58fb4879ef91"),
                            FirstName = "Herbert",
                            LastName = "Červinka",
                            Name = "Herbert84"
                        },
                        new
                        {
                            Id = new Guid("f6b2b031-3fb6-6af3-0d00-4ac25a8f24fa"),
                            Description = "My co-worker Matthew has one of these. He says it looks gigantic.",
                            FirstName = "Virgin",
                            LastName = "Motl",
                            Name = "Virgin_Motl11"
                        },
                        new
                        {
                            Id = new Guid("39c94d28-ccc4-6bf8-4d01-17aabd077878"),
                            Description = "My demon loves to play with it.",
                            FirstName = "Felicie",
                            LastName = "Šafránková",
                            Name = "Felicie_Safrankova53"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
